version: '3.8'
services: 
  api:
    build: .
    container_name: padosi-fastapi-docker-v2
    env_file:
      - ./app/.env
    ports: 
      - 8000:80
    volumes: 
      - ./api:/api
      - ./upload-images/:/upload-images/user/

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    ports:
      - 5430:5430
volumes:
    postgres_data: