"""empty message

Revision ID: 25e069916f9c
Revises: 26631dc2882f
Create Date: 2022-11-26 15:38:55.866778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e069916f9c'
down_revision = '26631dc2882f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'choice_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('choice_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
