"""empty message

Revision ID: 26631dc2882f
Revises: 
Create Date: 2022-11-26 15:12:22.642532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26631dc2882f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.String(length=200), nullable=True),
    sa.Column('question_text', sa.String(length=200), nullable=True),
    sa.Column('pub_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'choice', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'choice', type_='foreignkey')
    op.drop_table('question')
    # ### end Alembic commands ###
