"""empty message

Revision ID: 3965e376bbc1
Revises: b8f1c1f6ae05
Create Date: 2022-11-23 21:42:17.685665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3965e376bbc1'
down_revision = 'b8f1c1f6ae05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
