"""empty message

Revision ID: 44931509a319
Revises: 7ad63680d7b4
Create Date: 2022-11-24 12:55:06.305198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44931509a319'
down_revision = '7ad63680d7b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('likes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('likes', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('likes', sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'is_deleted')
    op.drop_column('likes', 'updated_at')
    op.drop_column('likes', 'created_at')
    op.drop_column('comments', 'is_deleted')
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
