"""empty message

Revision ID: 686123762b19
Revises: 25e069916f9c
Create Date: 2022-11-26 16:19:10.494374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686123762b19'
down_revision = '25e069916f9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('choice_text', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'choice_text')
    # ### end Alembic commands ###
