"""empty message

Revision ID: 7ad63680d7b4
Revises: 3965e376bbc1
Create Date: 2022-11-23 22:32:39.160469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad63680d7b4'
down_revision = '3965e376bbc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=False))
    op.drop_column('userprofiles', 'latitude')
    op.drop_column('userprofiles', 'longitude')
    op.drop_column('userprofiles', 'profile_complete_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofiles', sa.Column('profile_complete_percent', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('userprofiles', sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('userprofiles', sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'is_deleted')
    op.drop_column('posts', 'updated_at')
    # ### end Alembic commands ###
